### ISSUE TITLE
[ThemeLibrary] My theme was submitted without prior request of consent. I am not happy

### ISSUE THREAD

**Issue by Riddim-GLiTCH** [Faf4a/plugins#1]
Hi there. I am Riddim_GLiTCH, the author of [Virtual Boy](https://github.com/Riddim-GLiTCH/Virtual-Boy)

I recently learned that my theme is being shared through your plugin "ThemeLibrary" without my knowledge. I am not happy about this. I feel like my right as the theme author has been violated in a way as I do now know what version of the theme has been submitted and what potential modifications have been made to it. I am aware that the repo does not have a license yet, I am still working on figuring out how licensing works. but the readme states that crediting me and the contributors listed must be mentioned by name when redistributing. See https://github.com/Riddim-GLiTCH/Virtual-Boy#can-i-modify-this-theme-for-personal-use

I do not intend for my theme to be taken down. However, I wish I was at the very least asked for permission before my work is redistributed..

**Comment by RobinRMC** [comment]
> Hi there. I am Riddim_GLiTCH, the author of [Virtual Boy](https://github.com/Riddim-GLiTCH/Virtual-Boy)
> 
> I recently learned that my theme is being shared through your plugin "ThemeLibrary" without my knowledge. I am not happy about this. I feel like my right as the theme author has been violated in a way as I do now know what version of the theme has been submitted and what potential modifications have been made to it. I am aware that the repo does not have a license yet, I am still working on figuring out how licensing works. but the readme states that crediting me and the contributors listed must be mentioned by name when redistributing. See https://github.com/Riddim-GLiTCH/Virtual-Boy#can-i-modify-this-theme-for-personal-use
> 
> I do not intend for my theme to be taken down. However, I wish I was at the very least asked for permission before my work is redistributed..

As far as I know, the plugin pulls themes from the official sources. This means that your theme isn't included in the code.

**Comment by Riddim-GLiTCH** [comment]
I've seen themes in the list that I can't find on https://betterdiscord.app/themes, so unless it's pulling from multiple sources at once that I don't know of, I highly doubt that. This idea is reinforced by the fact that the plugin has a submission page.

**Comment by Faf4a** [comment]
Hello @Riddim-GLiTCH, as @RobinRMC I'm pulling the data from [betterdiscord.app/themes](https://api.betterdiscord.app/latest/store/themes), where not all themes are listed.

The authors are credited via the theme modal, if that's not enough feel free to tell me and I'll promptly remove your theme.

You can see the theme source also embedded by clicking "View Theme Info" -> "Theme Source" which shows you the whole **unmodified** source. I do not intend to modify anything that's on there.

Apologies for not asking in advance.

**Comment by Faf4a** [comment]
To not make this repeat:

- Added a banner explaining how to remove your theme in the plugin.
- Added a removal request form.
- Source now redirects to the given `@source` to comply with your request.

**Comment by Faf4a** [comment]
Also last comment on this from my side,

All theme data can be viewed in [the assets folder](https://github.com/Faf4a/plugins/blob/main/assets/meta.json#L1555-L1577), where it displays the content, version, author, name & everything else which is used from my side.

**Comment by Faf4a** [comment]
closing this due inactivity
